"""
typesdb_nt.py - Generated named tuples corresponding to each MakeTypesDB class
"""


from collections import namedtuple


# Each tuple below defines the name of a class and its attributes that must
# be filled in to insert an instance of that class in the db.
#
# The _i part means "instance".
#
# The list of attributes of each tuple matches the corresponding .xcm file in
# the types_domain directory. Do not edit this file as it is automatically generated each
# time the types_domain db is rebuilt.




# Type subsystem
Base_Type_i = namedtuple('Base_Type_i', 'Name')
Boolean_Symbol_Pair_i = namedtuple('Boolean_Symbol_Pair_i', 'Component User_type False_symbol True_symbol')
Component_i = namedtuple('Component_i', 'Name User_type')
Constraint_i = namedtuple('Constraint_i', 'Component User_type')
General_Rule_i = namedtuple('General_Rule_i', 'Component User_type General_Rule')
Implementation_i = namedtuple('Implementation_i', 'Platform Base_type Physical_type')
Inheritance_i = namedtuple('Inheritance_i', 'User_type Inherited_type')
Integer_Range_i = namedtuple('Integer_Range_i', 'Component User_type')
Integer_Subrange_i = namedtuple('Integer_Subrange_i', 'Component User_type Min Min_inclusive Max Max_inclusive')
Operator_i = namedtuple('Operator_i', 'Name Type')
Operator_Exclusion_i = namedtuple('Operator_Exclusion_i', 'Operator Inherited_type New_type')
Operand_i = namedtuple('Operand_i', 'Position Operator Type Operand_type')
Platform_i = namedtuple('Platform_i', 'Name')
Property_i = namedtuple('Property_i', 'Name Type')
Rational_Range_i = namedtuple('Rational_Range_i', 'Component User_type')
Rational_Subrange_i = namedtuple('Rational_Subrange_i', 'Component User_type Min Min_inclusive Max Max_inclusive')
Regular_Expression_i = namedtuple('Regular_Expression_i', 'Component User_type Regex')
Symbol_i = namedtuple('Symbol_i', 'Name Component User_type')
Symbol_Set_i = namedtuple('Symbol_Set_i', 'Component User_type')
Type_i = namedtuple('Type_i', 'Name')
User_Type_i = namedtuple('User_Type_i', 'Name Category')
Value_Subset_i = namedtuple('Value_Subset_i', 'Component User_type Constrained_type')